# Generated by Django 5.1 on 2025-04-15 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=150)),
                ('movie', models.CharField(max_length=100)),
                ('number_of_seats', models.IntegerField()),
                ('booking_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('show_time', models.CharField(max_length=100)),
                ('total_seats', models.IntegerField()),
                ('remaining_seats', models.IntegerField()),
                ('price', models.FloatField()),
            ],
        ),
    ]
