# Generated by Django 5.2 on 2025-04-24 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_feedback'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='show_time',
            field=models.DateTimeField(),
        ),
    ]
