# Generated by Django 5.2 on 2025-04-24 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_alter_movie_show_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='show_time',
            field=models.CharField(max_length=100),
        ),
    ]
