# Generated by Django 5.2 on 2025-04-24 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_alter_movie_show_time'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Movie',
        ),
    ]
