# Generated by Django 5.2 on 2025-04-24 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_delete_movie'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('show_time', models.CharField(max_length=100)),
                ('total_seats', models.IntegerField()),
                ('remaining_seats', models.IntegerField()),
                ('price', models.FloatField()),
            ],
        ),
    ]
